New event for January
pathfindertools/pl-network-events pull request #17
Opened 2023-01-10 15:44 UTC by cryptotwilight

This event will introduce attendees to the basics of blockchain and decentralized storage as provided on IPFS. It will be your opportunity ask questions and gain answers on the foundations of the Web3 Evolution. This event will be presented in both German and English. We will also have mini workshops that show you how to use Web3 to apply for roles on JobCrypt so if you're early you might get some free crypto. If not fear not we have more swag to give away through the course of the evening, so do join us.

2023-01-13 23:48 UTC, pandeyanujk approved these changes
Thanks for submitting!

2023-01-13 23:51 UTC, pandeyanujk commented on content/events/jobcrypt-web3-&-blockchain-talks-munich-germany.md
> +website: [https://www.jobcrypt.com/pages/promotions/munich/2023-01-25-In-Person-Talk.html](https://www.jobcrypt.com/pages/promotions/munich/2023-01-25-In-Person-Talk.html)
@cryptotwilight can you please change this from markdown to just URL "https://..."

Thanks!

2023-01-13 23:52 UTC, pandeyanujk requested changes
See - https://github.com/pathfindertools/pl-network-events/pull/17/files#r1070166833

2023-01-16 01:31 UTC, pandeyanujk approved these changes

2023-01-16 17:23 UTC, merged

2023-01-16 18:00 UTC, tbenbow commented
Thanks for this @cryptotwilight - this PR has been merged.